info:
  id: ${spring.application.name}

server:
  port: 8071

eureka:
  client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
        registerWithEureka: false
        fetchRegistry: false

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product
