info:
  id: ${spring.application.name}

server:
  port: 8081

eureka:
  client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
        registerWithEureka: false
        fetchRegistry: false

spring:
  data:
    rest:
      base-path: /
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest