info:
  id: ${spring.application.name}

server:
  port: 8082

eureka:
  client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
        registerWithEureka: false
        fetchRegistry: false

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        orderQ:
          destination: orderQ